[package]
name = "rcp2ctl"
description = "Linux control tool for the RØDECaster Pro II (CLI, then TUI)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rcp2-proto = { path = "../rcp2-proto" }

[lints]
workspace = true
