//! Generation of the PipeWire configuration declaring the named virtual sinks.

use std::fmt::Write as _;

use crate::channel::Channel;
use crate::graph::Rode;

/// File name of the generated configuration, inside `pipewire.conf.d`.
pub const CONFIG_FILE_NAME: &str = "50-rodecaster-virtual-sinks.conf";

/// First bytes of every configuration this project generates: how a file is
/// recognised as ours.
pub const GENERATED_MARKER: &str = "# Generated by rcp2ctl";

/// Error while generating the configuration.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("refusing to write node name `{0}` into the PipeWire config: unexpected characters")]
pub struct UnsafeNodeName(pub String);

/// Node names come from the system: only accept the characters ALSA and
/// PipeWire produce, so nothing can break out of the quoted config string.
pub(crate) fn check_node_name(name: &str) -> Result<&str, UnsafeNodeName> {
    let safe = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | ':'));
    if safe {
        Ok(name)
    } else {
        Err(UnsafeNodeName(name.to_owned()))
    }
}

/// Builds the PipeWire configuration declaring one loopback per [`Channel`]:
/// a stereo sink named after the channel, copied without remixing onto the
/// channel's pair of the board's native sink.
///
/// The output is deterministic, so regenerating it is idempotent.
///
/// # Errors
///
/// Returns [`UnsafeNodeName`] if a native sink name contains characters that
/// could not be written safely into the configuration.
pub fn pipewire_config(rode: &Rode) -> Result<String, UnsafeNodeName> {
    let mut out = String::from(
        "# Generated by rcp2ctl (rodecasterpro2-linux): named virtual outputs for the\n\
         # RØDECaster Pro II. Managed by `rcp2ctl persist on|off`: do not edit.\n\
         # `rcp2ctl persist off` restores exactly what was here before.\n\
         context.modules = [\n",
    );
    for channel in Channel::ALL {
        let target = check_node_name(rode.sink(channel.native_sink()))?;
        let [left, right] = channel.positions();
        // Writing to a String cannot fail.
        let _ = write!(
            out,
            r#"  {{ name = libpipewire-module-loopback
    args = {{
      node.description = "{description}"
      capture.props = {{
        node.name      = "{sink}"
        media.class    = "Audio/Sink"
        audio.position = [ FL FR ]
      }}
      playback.props = {{
        node.name          = "{sink}.output"
        node.passive       = true
        target.object      = "{target}"
        audio.position     = [ {left} {right} ]
        stream.dont-remix  = true
        node.dont-fallback = true
      }}
    }}
  }}
"#,
            description = channel.description(),
            sink = channel.sink_name(),
        );
    }
    out.push_str("]\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::{check_node_name, pipewire_config};
    use crate::graph::Rode;

    fn rode() -> Rode {
        Rode {
            stereo_sink: "alsa_output.usb-R__DE_RODECaster_Pro_II_TESTSERIAL-00.pro-output-0"
                .to_owned(),
            multi_sink: "alsa_output.usb-R__DE_RODECaster_Pro_II_TESTSERIAL-00.pro-output-1"
                .to_owned(),
        }
    }

    #[test]
    fn starts_with_the_generated_marker() {
        assert!(
            pipewire_config(&rode())
                .unwrap()
                .starts_with(super::GENERATED_MARKER)
        );
    }

    #[test]
    fn declares_one_loopback_per_channel() {
        let config = pipewire_config(&rode()).unwrap();
        assert_eq!(config.matches("libpipewire-module-loopback").count(), 6);
    }

    #[test]
    fn rejects_names_that_could_escape_the_string() {
        assert!(check_node_name("evil\" } ] context.exec = [").is_err());
        assert!(check_node_name("line\nbreak").is_err());
        assert!(check_node_name("").is_err());
        assert!(check_node_name(&rode().multi_sink).is_ok());
    }

    #[test]
    fn unsafe_sink_name_fails_generation() {
        let mut bad = rode();
        bad.multi_sink.push('"');
        assert!(pipewire_config(&bad).is_err());
    }
}
