//! The systemd user unit running `rcp2ctl daemon` (no root).

use std::path::{Path, PathBuf};
use std::process::Command;

use rcp2_audio::{config_home, write_atomically};

use crate::CliError;

/// Unit name, also the file name under `~/.config/systemd/user/`.
pub(crate) const UNIT_NAME: &str = "rodecasterpro2-linux.service";

/// First line of every unit this project writes: how a file is recognised as ours.
const UNIT_MARKER: &str = "# Generated by rcp2ctl";

/// `~/.config/systemd/user/rodecasterpro2-linux.service`.
pub(crate) fn unit_path() -> Result<PathBuf, CliError> {
    Ok(config_home()?.join("systemd").join("user").join(UNIT_NAME))
}

/// The unit text, starting this very binary.
pub(crate) fn unit_text(exe: &Path) -> String {
    format!(
        "{UNIT_MARKER} (rodecasterpro2-linux). `rcp2ctl uninstall` removes it.\n\
         [Unit]\n\
         Description=RØDECaster Pro II board service (keeps the control session read)\n\
         \n\
         [Service]\n\
         ExecStart=\"{}\" daemon\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n",
        exe.display()
    )
}

/// State of the unit file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum UnitState {
    Absent,
    Ours,
    Foreign,
}

pub(crate) fn unit_state(path: &Path) -> Result<UnitState, CliError> {
    match std::fs::read_to_string(path) {
        Ok(text) if text.starts_with(UNIT_MARKER) => Ok(UnitState::Ours),
        Ok(_) => Ok(UnitState::Foreign),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(UnitState::Absent),
        Err(source) => Err(CliError::File {
            path: path.to_owned(),
            source,
        }),
    }
}

/// Runs `systemctl --user <args>`.
fn systemctl(args: &[&str]) -> Result<(), CliError> {
    let shown = format!("systemctl --user {}", args.join(" "));
    let status = Command::new("systemctl")
        .arg("--user")
        .args(args)
        .status()
        .map_err(|_| CliError::Systemctl(shown.clone()))?;
    if status.success() {
        Ok(())
    } else {
        Err(CliError::Systemctl(shown))
    }
}

/// Writes (or updates) the unit for `exe` and starts it now and at login.
pub(crate) fn install(exe: &Path) -> Result<PathBuf, CliError> {
    // Quotes, `%` and line breaks mean something to systemd: refuse them.
    let text = exe.to_string_lossy();
    if text.contains(['"', '%', '\\', '\n']) {
        return Err(CliError::UnsafeExePath(exe.to_owned()));
    }
    let path = unit_path()?;
    if unit_state(&path)? == UnitState::Foreign {
        return Err(CliError::ForeignFile(path));
    }
    write_atomically(&path, unit_text(exe).as_bytes())?;
    systemctl(&["daemon-reload"])?;
    systemctl(&["enable", "--now", UNIT_NAME])?;
    // Picks up a new binary path if the unit was already running.
    systemctl(&["restart", UNIT_NAME])?;
    Ok(path)
}

/// Stops and removes our unit; `false` if there was none.
pub(crate) fn remove() -> Result<bool, CliError> {
    let path = unit_path()?;
    match unit_state(&path)? {
        UnitState::Absent => Ok(false),
        UnitState::Foreign => Err(CliError::ForeignFile(path)),
        UnitState::Ours => {
            systemctl(&["disable", "--now", UNIT_NAME])?;
            rcp2_audio::remove_file_if_present(&path)?;
            systemctl(&["daemon-reload"])?;
            Ok(true)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{UNIT_MARKER, unit_text};
    use std::path::Path;

    #[test]
    fn the_unit_runs_this_binary_as_a_daemon() {
        let text = unit_text(Path::new("/home/u/.cargo/bin/rcp2ctl"));
        assert!(text.starts_with(UNIT_MARKER));
        assert!(text.contains("ExecStart=\"/home/u/.cargo/bin/rcp2ctl\" daemon\n"));
        assert!(text.contains("WantedBy=default.target"));
    }
}
